name: pro_image_editor
description: "A Flutter image editor: Seamlessly enhance your images with user-friendly editing features."
version: 8.0.4
homepage: https://github.com/hm21/pro_image_editor/
repository: https://github.com/hm21/pro_image_editor/
issue_tracker: https://github.com/hm21/pro_image_editor/issues/
documentation: https://github.com/hm21/pro_image_editor/


topics:
  - image-editor
  - image
  - photo
  - picture
  - editor

screenshots:
  - description: "Showcase from the image editor with the frosted-glass design"
    path: assets/showcase-frosted-glass.jpg
  - description: "Showcase from the image editor with the Whatsapp design"
    path: assets/showcase-whatsapp.jpg
  - description: "Showcase from the image editor with simple design"
    path: assets/showcase.jpg

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  emoji_picker_flutter: ^4.3.0
  http: ^1.3.0
  image: ^4.5.2
  mime: ^2.0.0
  vibration: ^3.1.1
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
  mockito: ^5.4.5
  network_image_mock: ^2.0.0

flutter:
  assets:
    - lib/web/web_worker.dart.js
    - lib/web/web_worker.dart.js.map
    - lib/web/web_worker.dart.wasm
  fonts:
   - family: ProImageEditorIcons
     fonts:
      - asset: assets/fonts/ProImageEditorIcons.ttf